# Generated by Django 3.1.4 on 2021-03-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_work_id', models.CharField(max_length=20, verbose_name='工作证号')),
                ('as_username', models.CharField(max_length=11, verbose_name='姓名')),
                ('as_password', models.CharField(max_length=20, verbose_name='密码')),
                ('as_cell_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('as_status', models.IntegerField(default=1, verbose_name='状态 1正常 2禁用')),
            ],
            options={
                'verbose_name': '管理员用户管理',
                'verbose_name_plural': '管理员用户管理',
            },
        ),
        migrations.CreateModel(
            name='book_borrow_back',
            fields=[
                ('bb_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='图书编号')),
                ('bb_people', models.CharField(max_length=20, verbose_name='借用人学号')),
                ('bb_borrow_date', models.DateTimeField(verbose_name='借书日期')),
                ('bb_back_date', models.DateTimeField(max_length=20, verbose_name='还书日期')),
            ],
            options={
                'verbose_name': '图书借阅管理',
                'verbose_name_plural': '图书借阅管理',
            },
        ),
        migrations.CreateModel(
            name='book_category',
            fields=[
                ('bc_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书分类id')),
                ('bc_info', models.CharField(max_length=20, verbose_name='图书分类描述')),
            ],
            options={
                'verbose_name': '图书分类管理',
                'verbose_name_plural': '图书分类管理',
            },
        ),
        migrations.CreateModel(
            name='notice_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_title', models.CharField(max_length=50, verbose_name='公告标题')),
                ('nm_content', models.CharField(max_length=2000, verbose_name='公告内容')),
                ('nm_time_created', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.CreateModel(
            name='student_user',
            fields=[
                ('s_no', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='学号')),
                ('s_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('s_sex', models.IntegerField(default=0, verbose_name='性别 0男 1女')),
                ('s_xi', models.CharField(max_length=30, verbose_name='院系')),
                ('s_pwd', models.CharField(max_length=12, verbose_name='密码')),
                ('s_email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('s_borrow_count', models.IntegerField(default=0, verbose_name='借书数量,最多不能超过10')),
                ('s_status', models.IntegerField(default=1, verbose_name='状态 1正常 2禁用')),
                ('s_time_created', models.DateTimeField(auto_now=True, verbose_name='读者注册时间')),
            ],
            options={
                'verbose_name': '读者管理',
                'verbose_name_plural': '读者管理',
            },
        ),
        migrations.CreateModel(
            name='book_info',
            fields=[
                ('bi_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='图书编号')),
                ('bi_name', models.CharField(max_length=100, verbose_name='图书名称')),
                ('bi_publish_name', models.CharField(max_length=100, verbose_name='出版社名称')),
                ('bi_price', models.CharField(max_length=10, verbose_name='图书价格')),
                ('bi_author', models.CharField(max_length=10, verbose_name='作者')),
                ('bi_publish_date', models.CharField(max_length=10, verbose_name='出版日期')),
                ('bi_count', models.IntegerField(default=1, verbose_name='图书数量')),
                ('bi_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book_category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '图书信息管理',
                'verbose_name_plural': '图书信息管理',
            },
        ),
    ]
