# Generated by Django 3.1.4 on 2021-03-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_work_id', models.CharField(max_length=20, verbose_name='员工编号')),
                ('as_username', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('as_password', models.CharField(max_length=20, verbose_name='密码')),
                ('as_cell_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('as_status', models.IntegerField(default=1, verbose_name='账号状态 1正常 2禁用')),
            ],
            options={
                'verbose_name': '管理员用户管理',
                'verbose_name_plural': '管理员用户管理',
            },
        ),
        migrations.CreateModel(
            name='book_borrow_back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_number', models.CharField(max_length=20, verbose_name='图书编号')),
                ('bb_people', models.CharField(max_length=20, verbose_name='借用人学号')),
                ('bb_borrow_date', models.DateField(auto_now=True, verbose_name='借书日期')),
                ('bb_back_date', models.DateField(max_length=20, verbose_name='还书日期')),
                ('bb_state', models.IntegerField(default=0, verbose_name='借书状态:0-待借阅 1-借阅中 2-已归还  3-续借 4-申请中')),
                ('frequency', models.IntegerField(default=0, verbose_name='图书续借次数，只能续借一次')),
                ('bb_comment', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '图书借阅管理',
                'verbose_name_plural': '图书借阅管理',
            },
        ),
        migrations.CreateModel(
            name='book_category',
            fields=[
                ('bc_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书分类id')),
                ('bc_info', models.CharField(max_length=20, verbose_name='图书分类描述')),
            ],
            options={
                'verbose_name': '图书分类管理',
                'verbose_name_plural': '图书分类管理',
            },
        ),
        migrations.CreateModel(
            name='notice_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_title', models.CharField(max_length=50, verbose_name='公告标题')),
                ('nm_content', models.CharField(max_length=2000, verbose_name='公告内容')),
                ('nm_time_created', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.CreateModel(
            name='student_user',
            fields=[
                ('s_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('s_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('s_sex', models.IntegerField(default=0, verbose_name='性别 0男 1女')),
                ('s_xi', models.CharField(max_length=30, verbose_name='读者院系')),
                ('s_pwd', models.CharField(max_length=12, verbose_name='密码')),
                ('s_email', models.CharField(max_length=50, verbose_name='电子邮箱')),
                ('s_borrow_count', models.IntegerField(default=0, verbose_name='借书数量,最多不能超过10')),
                ('s_status', models.IntegerField(default=1, verbose_name='账号状态 1正常 2禁用')),
                ('s_cell_phone', models.CharField(max_length=20, verbose_name='读者联系电话')),
                ('s_time_created', models.DateTimeField(auto_now=True, verbose_name='读者注册时间')),
            ],
            options={
                'verbose_name': '读者管理',
                'verbose_name_plural': '读者管理',
            },
        ),
        migrations.CreateModel(
            name='book_info',
            fields=[
                ('bi_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书ISBN')),
                ('bi_name', models.CharField(max_length=50, verbose_name='图书名称')),
                ('bi_publish_name', models.CharField(max_length=30, verbose_name='出版社名称')),
                ('bi_price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='图书价格')),
                ('bi_author', models.CharField(max_length=10, verbose_name='作者')),
                ('bi_publish_date', models.DateField(verbose_name='出版日期')),
                ('bi_sn_number', models.CharField(max_length=30, verbose_name='SN号')),
                ('bi_status', models.IntegerField(default=1, verbose_name='图书状态：1-正常 2-损坏')),
                ('bi_caseid', models.CharField(max_length=20, verbose_name='书架编号')),
                ('bi_time_created', models.DateTimeField(auto_now=True, verbose_name='入馆时间')),
                ('bi_state', models.IntegerField(default=1, verbose_name='是否借出 0不在馆 1在馆')),
                ('bi_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book_category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '图书信息管理',
                'verbose_name_plural': '图书信息管理',
            },
        ),
        migrations.CreateModel(
            name='book_copy',
            fields=[
                ('bc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='副本编号')),
                ('bc_caseid', models.CharField(max_length=20, verbose_name='存放位置')),
                ('bc_state', models.IntegerField(default=1, verbose_name='是否借出 0不在馆 1在馆')),
                ('bc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book_info', verbose_name='图书ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='book_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_name', models.CharField(max_length=50, verbose_name='图书名称')),
                ('ba_author', models.CharField(max_length=50, verbose_name='图书作者')),
                ('ba_publish', models.CharField(max_length=50, verbose_name='图书出版社名称')),
                ('ba_price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='图书价格')),
                ('ba_status', models.IntegerField(default=0, verbose_name='处理状态:0-待处理 1-采购中 2-已到馆 3-驳回采购 4-取消申请')),
                ('ba_time_created', models.DateTimeField(auto_now=True, verbose_name='申请时间')),
                ('ba_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_user', verbose_name='申请人id')),
            ],
            options={
                'verbose_name': '图书预约管理',
                'verbose_name_plural': '图书预约管理',
            },
        ),
    ]
