# Generated by Django 3.1.4 on 2021-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='s_cell_phone',
            field=models.CharField(default=13456788900, max_length=11, verbose_name='读者联系电话'),
            preserve_default=False,
        ),
    ]
