# Generated by Django 3.1.4 on 2021-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_user_s_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='bi_sn_number',
            field=models.CharField(default=121414, max_length=30, verbose_name='SN号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_info',
            name='bi_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='bi_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='图书价格'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='bi_publish_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='bi_publish_name',
            field=models.CharField(max_length=30, verbose_name='出版社名称'),
        ),
    ]
