# Generated by Django 3.1.4 on 2021-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210314_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='bi_status',
            field=models.IntegerField(default=1, verbose_name='图书状态：1-正常 2-损坏'),
        ),
    ]
