# Generated by Django 3.1.4 on 2021-03-14 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_info_bi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='bi_count',
        ),
        migrations.AddField(
            model_name='book_info',
            name='bi_caseid',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='书架编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_info',
            name='bi_state',
            field=models.IntegerField(default=1, verbose_name='是否借出 0未借 1借出'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='bi_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入馆时间'),
            preserve_default=False,
        ),
    ]
