# Generated by Django 3.1.4 on 2021-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210314_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='bi_state',
            field=models.IntegerField(default=1, verbose_name='是否借出 0不在馆 1在馆'),
        ),
    ]
