# Generated by Django 3.1.4 on 2021-03-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210314_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='bi_time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='入馆时间'),
        ),
    ]
