# Generated by Django 3.1.4 on 2021-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210315_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_borrow_back',
            name='bb_comment',
            field=models.CharField(default='test', max_length=200, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_borrow_back',
            name='bb_state',
            field=models.IntegerField(default=1, verbose_name='借书状态:1-正在借阅 2-已归还  3-续借'),
        ),
        migrations.AddField(
            model_name='book_borrow_back',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_number',
            field=models.CharField(max_length=10, verbose_name='图书编号'),
        ),
    ]
