# Generated by Django 3.1.4 on 2021-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210316_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_back_date',
            field=models.DateField(max_length=20, verbose_name='还书日期'),
        ),
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_borrow_date',
            field=models.DateField(auto_now=True, verbose_name='借书日期'),
        ),
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_number',
            field=models.CharField(max_length=20, verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_state',
            field=models.IntegerField(default=0, verbose_name='借书状态:0-待借阅 1-正在借阅 2-已归还  3-续借'),
        ),
    ]
