# Generated by Django 3.1.4 on 2021-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210316_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_state',
            field=models.IntegerField(default=0, verbose_name='借书状态:0-待借阅 1-借阅中 2-已归还  3-续借'),
        ),
    ]
