# Generated by Django 3.1.4 on 2021-03-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210317_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_borrow_back',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='图书续借次数，只能续借一次'),
        ),
    ]
