# Generated by Django 3.1.4 on 2021-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210317_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_name', models.CharField(max_length=50, verbose_name='图书名称')),
                ('ba_author', models.CharField(max_length=50, verbose_name='图书作者')),
                ('ba_publish', models.CharField(max_length=50, verbose_name='图书出版社名称')),
                ('ba_price', models.FloatField(verbose_name='图书价格')),
                ('ba_status', models.IntegerField(default=0, verbose_name='处理状态:0-待处理 1-采购中 2-已到馆 3-驳回采购')),
            ],
            options={
                'verbose_name': '图书预约管理',
                'verbose_name_plural': '图书预约管理',
            },
        ),
        migrations.AlterField(
            model_name='book_borrow_back',
            name='bb_state',
            field=models.IntegerField(default=0, verbose_name='借书状态:0-待借阅 1-借阅中 2-已归还  3-续借 4-申请中'),
        ),
    ]
