# Generated by Django 3.1.4 on 2021-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210321_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_apply',
            name='ba_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='图书价格'),
        ),
    ]
