# Generated by Django 3.1.4 on 2021-03-21 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210321_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_apply',
            name='ba_user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.student_user', verbose_name='申请人id'),
            preserve_default=False,
        ),
    ]
