# Generated by Django 3.1.4 on 2021-03-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_book_apply_ba_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_apply',
            name='ba_time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='申请时间'),
        ),
    ]
