# Generated by Django 3.1.4 on 2021-03-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_book_apply_ba_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_apply',
            name='ba_status',
            field=models.IntegerField(default=0, verbose_name='处理状态:0-待处理 1-采购中 2-已到馆 3-驳回采购 4-取消申请'),
        ),
    ]
