# Generated by Django 3.1.4 on 2021-03-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210323_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='bi_name',
            field=models.CharField(max_length=50, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='bi_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书ISBN'),
        ),
        migrations.CreateModel(
            name='book_copy',
            fields=[
                ('bc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='副本编号')),
                ('bc_caseid', models.CharField(max_length=20, verbose_name='存放位置')),
                ('bc_state', models.IntegerField(default=1, verbose_name='是否借出 0不在馆 1在馆')),
                ('bc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book_info', verbose_name='图书ISBN')),
            ],
        ),
    ]
