# Generated by Django 3.1.4 on 2021-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210323_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='as_cell_phone',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='as_status',
            field=models.IntegerField(default=1, verbose_name='账号状态 1正常 2禁用'),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='as_username',
            field=models.CharField(max_length=20, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='as_work_id',
            field=models.CharField(max_length=20, verbose_name='员工编号'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='s_cell_phone',
            field=models.CharField(max_length=20, verbose_name='读者联系电话'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='s_email',
            field=models.CharField(max_length=50, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='s_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='s_status',
            field=models.IntegerField(default=1, verbose_name='账号状态 1正常 2禁用'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='s_xi',
            field=models.CharField(max_length=30, verbose_name='读者院系'),
        ),
    ]
